### PR TITLE
More knob dialog improvements

### PR DESCRIPTION
**Pull request by timothyschoen**
- Added comments to tcl/tk file
- Added arc colour
- Added outline toggle box
- Fixed send/receive error message when unbinding "empty"

- Maybe fixed the dollar signs, but not sure, I'll test it more later

If you can explain the idea of the log behaviour we want to me, that would help

### CODE REVIEW

**Comment by porres** [comment]
'arc' color should maybe be called 'middle' and come in the middle

When setting the send name with "$0" inside properties it gets lost when properties are reopened, when setting it via a message it also does not get shown inside properties, so we failed it somehow

**Comment by porres** [comment]
x_expmode should be set from properties, we just don't need to save it as an argument. The mode is easy to set from the interface. The exp value shold also be set from the properties. 

now, exp = 0 means linear, = 1 means log, other values mean exp

**Comment by timothyschoen** [comment]
> 'arc' color should maybe be called 'middle' and come in the middle

If you want this I'll do it, but I think it's a lot less clear than "arc". Middle could easily be interpreted as being about the centre of the button, but that's the background colour.

> now, exp = 0 means linear, = 1 means log, other values mean exp

So I think this might not be a good idea, here's why:
- If we keep the UI the same, we can't properly restore the checkbox if the user enters "0" or "1" in the exp text input.
- If we only have a textbox in the UI (so you directly enter the value of exp where exp = 0 means linear, exp = 1 means log), it makes it very unclear how it works. The checkbutton is self-documenting, only having a text input is not (you'd have to look up the values for linear and log, and if you're not aware of how it works, you'll easily get confused).

**Comment by porres** [comment]
for no better word I have now mgcolor... arc color may not be that confusing, I was thinking that the actual color of the arc is the front color, but then "arc bg" should be the best fit for the properties, and it should come in the middle to make sense... not sure what to do with the messages though yet

> now, exp = 0 means linear, = 1 means log, other values mean exp

note that this is just under the hood, not something exposed to the user. This is just how the exp arg gets saved and restored. Also, values of 1 and -1 get considered linear and thus they become zero! So you will never have the object saving the arg as -1, which gives us yet another slot for coming up later with yet some other option, haha....

> If we keep the UI the same, we can't properly restore the checkbox if the user enters "0" or "1" in the exp text input.

for the user I think we should expose that "0", "1" or "-1" will set it to linear, so it's linear when you reopen it. Now, the thing is that the tcl tk side needs to gather this information from what the user sets in the properties.

if the linear slot is checked, then it has to set **_x->x_expmode_** to zero and the **_x->x_exp_** arg to zero as well. If the log slot is taken instead, then both are to be set as equal to 1! Got it? So if the user sets the exp box's value, then expmode is 2 and the exp variable gets whatever it is set, but we have to whatch if the user includes  "0", "1" or "-1", cause it'll become linear (expmode and exp equal to zero)!

**Comment by porres** [comment]
> I understand this, but what I don't understand is why removing the expmode output from tcl/tk is necessary or useful.

i didnt mean to remove it from tcl tk

**Comment by timothyschoen** [comment]
> > I understand this, but what I don't understand is why removing the expmode output from tcl/tk is necessary or useful.
> 
> i didnt mean to remove it from tcl tk

Oh now I don't understand it anymore, do I only need to change something in C? I thought this was a problem with the properties dialog?

> I don't think people will change modes and stuff via messages much, like back and forth, they'll probably just use properties in the same way I never use messages for iemguis. Once they find the right setting, they'll stick to it and not change ever again either via properties or messages.

true, fine with me.

**Comment by porres** [comment]
> do I only need to change something in C?

no

> I thought this was a problem with the properties dialog?

yes, we need to work on the data on the properties and get the expmode and everything to feed it back to the C side... using the same logic that I exposed

**Comment by timothyschoen** [comment]
Okay, I really want to finish this today but I still don't fully understand what you need me to do.

What I understand right now, is that the tcl/tk dialog should only input/output an "exp" value and no "expmode" value. This is purely an implementation thing, not user facing right?

So basically the only effect this will have for the user, is that if you enter "0" in the exp textbox, then close/reopen the dialog, we can no longer know for sure what checkbox was checked, so the user gets this weird effect where, in their eyes, the settings changed automatically.

Or do you want me make the "log" and "lin" button automatically get checked when you enter "0" or "1" in the exp textbox? I think that would also be kind of annoying.

**Comment by porres** [comment]
right now, setting things via properties simply don't work... I can't get the right settings for the log, lin or exp... I could say just do whatever it needs to be done in the tcl tk side so it works....

> What I understand right now, is that the tcl/tk dialog should only input/output an "exp" value and no "expmode" value. This is purely an implementation thing, not user facing right?

no I didn't mean that at all, all I said is that we should not have an expmode message to the user... the x->x_expmode variable in the code could and should stay to make things easier and we already use it to send info to the properties window anyway. The user doesnt have to be aware of it though.

what I actually said was to set x->x_expmode and x->x_exp from the data set via the properties window, with the logic I already exposed.

> Or do you want me make the "log" and "lin" button automatically get checked when you enter "0" or "1" in the exp textbox? I think that would also be kind of annoying.

agreed, no, annoying and I never asked that. In fact, "0", "1" or "-1" should make it linear! That's what I explained. But the user should be able to set it and when reopening the window the linear checkbox would be checked.

I'm sorry this is confusing, I figured it would be as straightforward as possible, again, it's just not working and we need to apply some simple logic to make it happen.

**Comment by timothyschoen** [comment]
Got it, thanks for explaining it again :)

**Pull request merged**
