### PR TITLE
Cleaned up a lot of trash, added discrete setting, better normal/log/exp selection, fixed conflicts with iem dialog

### PR DESCRIPTION
**Pull request by timothyschoen**

### CODE REVIEW

**Comment by timothyschoen** [comment]
Currently known issues:

- Colours don't work
- Send/receive don't work

I'll try to fix that tomorrow

**Comment by porres** [comment]
funny, doesn't work for me :(

I created a new object and, ok, it got created, but when trying to ask for properties Pd blew up....

**Comment by porres** [comment]
fixed it

**Comment by porres** [comment]
now saving blows it up :)

**Comment by porres** [comment]
fixing it too

**Comment by porres** [comment]
fixed

**Comment by porres** [comment]
> I'll try to fix that tomorrow

let me work on this a bit and then hand it back to you

THANKS!

**Pull request merged**
